export const V3_ROUTER_ABI = {
  address: "0xa746b0fc9bf1e391d10836d6d14fbf362960e78c0b522c238253ca9a67b82de5",
  name: "router",
  friends: [],
  exposed_functions: [
    {
      name: "simulate_in_given_out",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "vector<address>",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
      ],
      return: ["u64"],
    },
    {
      name: "simulate_out_given_in",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "vector<address>",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
      ],
      return: ["u64"],
    },
    {
      name: "swap_exact_in_router_entry",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "vector<address>",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "0x1::string::String",
      ],
      return: [],
    },
    {
      name: "swap_exact_out_router_entry",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "vector<address>",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u64",
        "0x1::string::String",
      ],
      return: [],
    },
    {
      name: "swap_route",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "vector<address>",
        "vector<0x1::object::Object<0x1::fungible_asset::Metadata>>",
        "0x1::fungible_asset::FungibleAsset",
        "0x1::string::String",
      ],
      return: ["0x1::fungible_asset::FungibleAsset"],
    },
  ],
  structs: [
    {
      name: "Notacoin",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "dummy_field",
          type: "bool",
        },
      ],
    },
  ],
} as const;
