export const V3_SCRIPT_ABI = {
  address: "0x4fcc5756d139e633b09bf7cb35347637b1031d24903bcf4d14613d5b58270b1a",
  name: "scripts",
  friends: [],
  exposed_functions: [
    {
      name: "swap",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x4fcc5756d139e633b09bf7cb35347637b1031d24903bcf4d14613d5b58270b1a::pool::Pool>",
        "bool",
        "u64",
        "u64",
        "u128",
        "bool",
      ],
      return: [],
    },
    {
      name: "add_liquidity",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x4fcc5756d139e633b09bf7cb35347637b1031d24903bcf4d14613d5b58270b1a::pool::Pool>",
        "u64",
        "u64",
        "u64",
        "u64",
        "bool",
        "u64",
        "bool",
      ],
      return: [],
    },
    {
      name: "collect_fees",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "0x1::object::Object<0x4::token::Token>"],
      return: [],
    },
    {
      name: "create_concentrated_pool",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
        "u128",
        "u64",
      ],
      return: [],
    },
    {
      name: "remove_liquidity",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x4::token::Token>",
        "u64",
        "u64",
        "u64",
      ],
      return: [],
    },
  ],
  structs: [],
} as const;
